apiVersion: v1
kind: Pod
metadata:
  name: allocator-test
  namespace: agones-system
  annotations:
    sidecar.istio.io/inject: "true"
spec:
  tolerations:
  - key: agones.dev/agones-system
    operator: Exists
    effect: NoExecute
  - key: CriticalAddonsOnly
    operator: Exists
  containers:
  - name: test
    image: nicolaka/netshoot
    command: ["sleep", "600"]
